-- Files are placed in lua/user/ directory to avoid namespace issues.
require("user.plugins")
require("user.options")
require("user.keymaps")
require("user.colorscheme")
require("user.treesitter")
require("user.cmp")
require("user.lsp")
require("user.nvim-tree")
require("user.telescope")
require("user.comment")
require("user.gitsigns")
require("user.trouble")
